const LABELS={mode:'Режим системы',battery:'Батарея',power:'Генерация',load:'Потребление',air:'Состав воздуха',temp:'Температура',link:'Связь',production:'Производство'};
const state={socket:null,retry:1000,messages:0,manualScroll:false};
const chat=document.querySelector('#chat'),cards=document.querySelector('#cards'),connection=document.querySelector('#connection'),updated=document.querySelector('#updated'),jump=document.querySelector('#jump');
function wsUrl(){const host=location.hostname||'localhost';return `ws://${host}:8766`;}
function setConnection(ok,text){connection.textContent=text;connection.className=`badge ${ok?'online':'offline'}`;document.querySelector('#operatorInput').disabled=!ok;}
function connect(){setConnection(false,'подключение…');const ws=new WebSocket(wsUrl());state.socket=ws;
 ws.onopen=()=>{state.retry=1000;setConnection(true,'онлайн');};
 ws.onmessage=e=>{try{handle(JSON.parse(e.data));}catch(err){console.error(err)}};
 ws.onclose=()=>{setConnection(false,'переподключение…');setTimeout(connect,state.retry);state.retry=Math.min(state.retry*1.7,10000)};
 ws.onerror=()=>ws.close();}
function handle(data){if(data.type==='history'){chat.innerHTML='';state.messages=0;(data.chat||[]).forEach(addMessage);renderCards(data.dashboard||{});return}if(data.type==='chat')addMessage(data.message);if(data.type==='dashboard')renderCards(data.params||{});if(data.type==='error')addMessage({type:'danger',agent:'Система',text:data.text,t:Date.now()/1000});}
function addMessage(m){const atBottom=chat.scrollHeight-chat.scrollTop-chat.clientHeight<90;const el=document.createElement('article');el.className=`message ${m.type||'agent'}`;const time=new Date((m.t||Date.now()/1000)*1000).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit'});el.innerHTML=`<div class="meta"><strong></strong><time>${time}</time></div><div class="text"></div>`;el.querySelector('strong').textContent=m.agent||'Система';el.querySelector('.text').textContent=m.text||'';chat.append(el);state.messages++;document.querySelector('#messageCount').textContent=`${state.messages} сообщений`;if(atBottom&&!state.manualScroll){chat.scrollTop=chat.scrollHeight}else jump.classList.add('show');}
function renderCards(snapshot){for(const key of Object.keys(LABELS)){let el=document.querySelector(`[data-card="${key}"]`);if(!el){el=document.createElement('div');el.dataset.card=key;el.className='card muted';el.innerHTML=`<div class="label">${LABELS[key]}</div><div class="value">—</div><div class="sub">нет данных</div>`;cards.append(el)}const d=snapshot[key]||{};el.className=`card ${d.level||'muted'}`;el.querySelector('.value').textContent=d.value??'—';el.querySelector('.sub').textContent=d.sub||'';}updated.textContent=`обновлено ${new Date().toLocaleTimeString('ru-RU')}`;}
document.querySelector('#composer').addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#operatorInput'),text=input.value.trim();if(!text||state.socket?.readyState!==WebSocket.OPEN)return;state.socket.send(JSON.stringify({type:'operator_message',text}));input.value='';});
chat.addEventListener('scroll',()=>{state.manualScroll=chat.scrollHeight-chat.scrollTop-chat.clientHeight>90;if(!state.manualScroll)jump.classList.remove('show')});jump.onclick=()=>{state.manualScroll=false;chat.scrollTop=chat.scrollHeight;jump.classList.remove('show')};connect();
